name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/727026638213/locations/global/workloadIdentityPools/accenture-lab-identitypool/providers/accenture-lab-identityprovider'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Configure Docker for Artifact Registry
      run: gcloud config list

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/accenture-intern/accenture-lab/static-site:${{ github.sha }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/accenture-intern/accenture-lab/static-site:${{ github.sha }}

    - name: Set project ID for gcloud CLI
      run: |
        gcloud config set project accenture-intern

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: 'static-frontend-service'
        image: 'us-central1-docker.pkg.dev/accenture-intern/accenture-lab/static-site:${{ github.sha }}'
        region: 'us-central1'
