name: Build & Push Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (via WIF + SA impersonation)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/927944170120/locations/global/workloadIdentityPools/accenture-identity-pool/providers/accenture-lab-indentityprovider"
          service_account: "cli-service-account-1@playground-s-11-88552fdb.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t asia-docker.pkg.dev/playground-s-11-88552fdb/my-docker-repo/my-image:latest .

      - name: Push image
        run: |
          docker push asia-docker.pkg.dev/playground-s-11-88552fdb/my-docker-repo/my-image:latest
